---
title: "Exploratory 1A Analysis Part 2"
output: html_document
---
# Load packages 
```{r message=FALSE, warning=FALSE, include=FALSE}

library(tidyverse)
library(extrafont)
library(here)
library(janitor)
library(gt)
library(webshot)
library(apa)
library(patchwork)
```

# Read and clean data 

```{r message=FALSE, warning=FALSE, include=FALSE}

data1A <- read_csv(here("data_files", "scored_master_dataset_1A.csv"))

# first, let's collapse the subfields into 4 main groups: developmental, cognition, social and 'other'
subfield_groups <- data1A %>%
  mutate(subfield_groups = case_when(subfield == "Behavioural Neuroscience" ~ "Other",
                                     subfield == "Cognitive Neuroscience" ~ "Other",
                                     subfield == "Health Psychology" ~ "Other",
                                     subfield == "Perception" ~ "Other",
                                     subfield == "Developmental Psychology" ~ "Development",
                                     subfield == "Social Psychology" ~  "Social",
                                     TRUE ~ as.character(subfield))) %>%
  relocate(subfield_groups, .after = subfield)

# we can now delete the original subfield column
subfield_groups <- subfield_groups %>%
  select(-subfield)
```

# DATA

Select only variables we're interested in

```{r message=FALSE, warning=FALSE, include=FALSE}
select_data <- subfield_groups  %>%
  select(article_id_number, subfield_groups, did_the_article_receive_a_badge_for_open_data, data_statement_indicates_that_data_are, are_the_data_located_at_the_working_page, does_the_data_correspond_to_what_is_reported_in_the_article, software, is_a_codebook_included_with_the_data_or_other_means_of_understanding_the_variables, are_analysis_scripts_included_with_the_data, are_the_data_complete)

```

Let's create some summary tables

```{r message=FALSE, warning=FALSE, include=FALSE}
# reportedly available
reportedly_available_data <- select_data %>%
  filter(did_the_article_receive_a_badge_for_open_data == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_data, data_statement_indicates_that_data_are) %>%
  mutate("Percent" = Available/(Available)*100) %>%
  select(Number = Available, Percent) %>%
  mutate(Real_Stage = "Reportedly Available")

# locatable data
locatable_data <- select_data %>%
  filter(did_the_article_receive_a_badge_for_open_data == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_data, are_the_data_located_at_the_working_page) %>%
  mutate("Percent" = Yes/(Yes)*100) %>%
  select(Number = Yes, Percent) %>%
  mutate(Real_Stage = "Actually Locatable")

# correct data 
correct_data <- select_data %>%
  filter(did_the_article_receive_a_badge_for_open_data == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_data, does_the_data_correspond_to_what_is_reported_in_the_article) %>%
  mutate("Percent" = Yes/(Yes + Unclear)*100) %>%
  select(Number = Yes, Percent) %>%
  mutate(Real_Stage = "Correct Data")

# complete data
complete_data <- select_data %>%
  filter(did_the_article_receive_a_badge_for_open_data == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_data, are_the_data_complete) %>%
  mutate("Percent" = `Yes, all of the data appear to be available`/(`Yes, all of the data appear to be available` + `Yes, but only some of the data are available` + `No, not all of the data are available` + `Unclear whether or not all of the data are available`)*100) %>%
  select(Number = `Yes, all of the data appear to be available`, Percent) %>%
  mutate(Real_Stage = "Complete Data")

# software specified
software_specified <- select_data %>%
  filter(did_the_article_receive_a_badge_for_open_data == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_data, software) %>%
  mutate("Percent" = Yes/(Yes + No)*100) %>%
  select(Number = Yes, Percent) %>%
  mutate(Real_Stage = "Software Specified")

# codebook available 
data_codebook_available <- select_data %>%
  filter(did_the_article_receive_a_badge_for_open_data == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_data, is_a_codebook_included_with_the_data_or_other_means_of_understanding_the_variables) %>%
  mutate("Percent" = Yes/(Yes + No)*100) %>%
  select(Number = Yes, Percent) %>%
  mutate(Real_Stage = "Codebook Available")

# scripts available 
data_scripts_available <- select_data %>%
  filter(did_the_article_receive_a_badge_for_open_data == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_data, are_analysis_scripts_included_with_the_data) %>%
  mutate("Percent" = Yes/(Yes + No)*100) %>%
  select(Number = Yes, Percent) %>%
  mutate(Real_Stage = "Scripts Available")
```

Let's bind all these statistics together

```{r echo=FALSE, message=FALSE, warning=FALSE}
all_data_stats <- rbind(reportedly_available_data, locatable_data, correct_data, complete_data, software_specified, data_codebook_available, data_scripts_available)
```

Let's plot

```{r}
data_plot <- ggplot(all_data_stats, aes(y=Percent, x = Real_Stage, group = 1)) + geom_line(colour = "#FF6666", size = 1) + geom_point(size = 3, colour = "#FF6666") +
  coord_cartesian(ylim=c(0,100)) +
  theme(axis.text.y = element_text(size=9),
        axis.title.y = element_text(size=7)) +
  theme(axis.text.x = element_text(size=7)) +
  scale_x_discrete(limits=c("Reportedly Available","Actually Locatable","Correct Data","Complete Data", "Codebook Available", "Software Specified", "Scripts Available")) +
  ylab("% of Articles Awarded with Open Data Badge") +
  theme(axis.line= element_line(), axis.title.x=element_blank(), 
        panel.background = element_blank(), 
        panel.grid.minor = element_blank()) 

data_plot
```

# MATERIALS

Select only the variables we're interested in

```{r message=FALSE, warning=FALSE, include=FALSE}
select_materials <- subfield_groups %>%
  select(article_id_number, subfield_groups, did_the_article_receive_a_badge_for_open_materials, statement_indicates_that_materials_are, are_the_materials_located_at_the_working_page, do_the_materials_correspond_to_what_is_reported_in_the_article, are_the_materials_complete, are_analysis_scripts_included_with_the_materials)
```

Let's create some summary tables

```{r message=FALSE, warning=FALSE, include=FALSE}
# reportedly available
reportedly_available_materials <- select_materials %>%
  filter(did_the_article_receive_a_badge_for_open_materials == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_materials, statement_indicates_that_materials_are) %>%
  mutate("Percent" = Available/(Available)*100) %>%
  select(Number = Available, Percent) %>%
  mutate(Real_Stage = "Reportedly Available")

# locatable materials
locatable_materials <- select_materials %>%
  filter(did_the_article_receive_a_badge_for_open_materials == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_materials, are_the_materials_located_at_the_working_page) %>%
  mutate("Percent" = Yes/(Yes)*100) %>%
  select(Number = Yes, Percent) %>%
  mutate(Real_Stage = "Actually Locatable")

# correct materials
correct_materials <- select_materials %>%
  filter(did_the_article_receive_a_badge_for_open_materials == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_materials, do_the_materials_correspond_to_what_is_reported_in_the_article) %>%
  mutate("Percent" = Yes/(Yes)*100) %>%
  select(Number = Yes, Percent) %>%
  mutate(Real_Stage = "Correct Materials")

# complete materials
complete_materials <- select_materials %>%
  filter(did_the_article_receive_a_badge_for_open_materials == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_materials, are_the_materials_complete) %>%
  mutate("Percent" = `Yes, all of the materials appear to be available`/(`Yes, all of the materials appear to be available` + `Yes, but only some of the materials are available` + `No, not all of the materials are available`)*100) %>%
  select(Number = `Yes, all of the materials appear to be available`, Percent) %>%
  mutate(Real_Stage = "Complete Materials")

# scripts available 
material_scripts_available <- select_materials %>%
  filter(did_the_article_receive_a_badge_for_open_materials == "Yes") %>%
  tabyl(did_the_article_receive_a_badge_for_open_materials, are_analysis_scripts_included_with_the_materials) %>%
  mutate("Percent" = Yes/(Yes + No)*100) %>%
  select(Number = Yes, Percent) %>%
  mutate(Real_Stage = "Scripts Available")
```

Let's bind all these statistics together

```{r message=FALSE, warning=FALSE, include=FALSE}
all_material_stats <- rbind(reportedly_available_materials, locatable_materials, correct_materials, complete_materials, material_scripts_available)

```

Let's plot

```{r}
materials_plot <- ggplot(all_material_stats, aes(y=Percent, x = Real_Stage, group = 1)) + geom_line(colour = "#6699CC", size = 1) + geom_point(size = 3, colour = "#6699CC") +
  coord_cartesian(ylim=c(0,100)) +
  theme(axis.text.y = element_text(size=9),
        axis.title.y = element_text(size=7)) +
  theme(axis.text.x = element_text(size=7)) +
  scale_x_discrete(limits=c("Reportedly Available","Actually Locatable","Correct Materials","Complete Materials", "Scripts Available")) +
  ylab("% of Articles Awarded with Open Materials Badge") +
  theme(axis.line= element_line(), axis.title.x=element_blank(), 
        panel.background = element_blank(), 
        panel.grid.minor = element_blank()) 

data_plot /
  materials_plot
```