---
title: "Exploratory 1A Analysis"
output: html_document
---

# Load packages 
```{r setup, include=FALSE}
library(tidyverse)
library(extrafont)
library(here)
```

# Read and clean data 

```{r cars}
data1A <- read_csv(here("data_files", "scored_master_dataset_1A.csv"))

# first, let's collapse the subfields into 4 main groups: developmental, cognition, social and 'other'
subfield_groups <- data1A %>%
  mutate(subfield_groups = case_when(subfield == "Behavioural Neuroscience" ~ "Other",
                                     subfield == "Cognitive Neuroscience" ~ "Other",
                                     subfield == "Health Psychology" ~ "Other",
                                     subfield == "Perception" ~ "Other",
                                     subfield == "Developmental Psychology" ~ "Development",
                                     subfield == "Social Psychology" ~  "Social",
                                     TRUE ~ as.character(subfield))) %>%
  relocate(subfield_groups, .after = subfield)

# we can now delete the original subfield column
subfield_groups <- subfield_groups %>%
  select(-subfield)
```

# DATA

Select only variables we're interested in

```{r pressure, echo=FALSE}
select_data <- subfield_groups  %>%
  select(article_id_number, subfield_groups, data_statement_indicates_that_data_are, are_the_data_located_at_the_working_page, does_the_data_correspond_to_what_is_reported_in_the_article, software, is_a_codebook_included_with_the_data_or_other_means_of_understanding_the_variables, are_analysis_scripts_included_with_the_data, are_the_data_complete)

```

Let's create some summary tables

```{r}
# reportedly available
reportedly_available_data <- select_data %>%
  filter(data_statement_indicates_that_data_are == "Available") %>%
  tabyl(subfield_groups, data_statement_indicates_that_data_are) %>%
  mutate("Percent" = Available/(Available)*100) %>%
  select(subfield_groups, Number = Available, Percent) %>%
  mutate(Real_Stage = "Reportedly Available")

# loctable data
locatable_data <- select_data %>%
  filter(data_statement_indicates_that_data_are == "Available") %>%
  tabyl(subfield_groups, are_the_data_located_at_the_working_page) %>%
  mutate("Percent" = Yes/(Yes + No + `Requires permission`)*100) %>%
  select(subfield_groups, Number = Yes, Percent) %>%
  mutate(Real_Stage = "Locatable Data")

# correct data 
correct_data <- select_data %>%
  filter(data_statement_indicates_that_data_are == "Available") %>%
  tabyl(subfield_groups, does_the_data_correspond_to_what_is_reported_in_the_article) %>%
  mutate("Percent" = Yes/(Yes + Unclear)*100) %>%
  select(subfield_groups, Number = Yes, Percent) %>%
  mutate(Real_Stage = "Correct Data")

# complete data
complete_data <- select_data %>%
  filter(data_statement_indicates_that_data_are == "Available") %>%
  tabyl(subfield_groups, are_the_data_complete) %>%
  mutate("Percent" = `Yes, all of the data appear to be available`/(`Yes, all of the data appear to be available` + `Yes, but only some of the data are available` + `No, not all of the data are available` + `Unclear whether or not all of the data are available`)*100) %>%
  select(subfield_groups, Number = `Yes, all of the data appear to be available`, Percent) %>%
  mutate(Real_Stage = "Complete Data")

# software specified
software_specified <- select_data %>%
  filter(data_statement_indicates_that_data_are == "Available") %>%
  tabyl(subfield_groups, software) %>%
  mutate("Percent" = Yes/(Yes + No)*100) %>%
  select(subfield_groups, Number = Yes, Percent) %>%
  mutate(Real_Stage = "Software Specified")

# codebook available 
data_codebook_available <- select_data %>%
  filter(data_statement_indicates_that_data_are == "Available") %>%
  tabyl(subfield_groups, is_a_codebook_included_with_the_data_or_other_means_of_understanding_the_variables) %>%
  mutate("Percent" = Yes/(Yes + No)*100) %>%
  select(subfield_groups, Number = Yes, Percent) %>%
  mutate(Real_Stage = "Codebook Available")

# scripts available 
data_scripts_available <- select_data %>%
  filter(data_statement_indicates_that_data_are == "Available") %>%
  tabyl(subfield_groups, are_analysis_scripts_included_with_the_data) %>%
  mutate("Percent" = Yes/(Yes + No)*100) %>%
  select(subfield_groups, Number = Yes, Percent) %>%
  mutate(Real_Stage = "Scripts Available")
```

Let's bind all these statistics together

```{r}
all_stats <- rbind(reportedly_available_data, locatable_data, correct_data, complete_data, software_specified, data_codebook_available, data_scripts_available)%>%
  relocate(subfield_groups, .after = `Real_Stage`) %>%
  relocate(Number, .after = subfield_groups) %>%
  relocate(Percent, .after = Number)

# let's add a column that specifies the "stage" of each variable
all_stats <- all_stats %>%
  mutate(Stage = case_when(Real_Stage == "Reportedly Available" ~ 1,
                           Real_Stage == "Locatable Data" ~ 2,
                           Real_Stage == "Correct Data" ~ 3,
                           Real_Stage == "Complete Data" ~ 4,
                           Real_Stage == "Codebook Available" ~ 5,
                           Real_Stage == "Software Specified" ~ 6,
                           Real_Stage == "Scripts Available" ~ 7))

```

Let's plot

```{r}
plot <- ggplot(all_stats, aes(y=Percent,  group = subfield_groups, colour = subfield_groups)) +
  coord_cartesian(ylim=c(0,100)) +
  geom_line(aes(size=subfield_groups, colour=subfield_groups, x=Real_Stage)) +
  geom_point(aes(x=Stage), size=8, shape=21, fill="white", position = position_dodge(width=0)) +
  geom_text(aes(x=Stage,
                label=Number,
                hjust=.5,
                vjust=.5),
            size=3,
            show.legend = F) +
  scale_color_manual(values=c("#E69F00","#009E73", "#D55E00", "#0072B2"),
                     labels=c("Development",
                              "Social",
                              "Cognition",
                              "Other")) +
  scale_size_manual(name= "subfield_groups",
                    values=c(2,
                             2,
                             2,
                             2),
                    guide=F) +
  theme(axis.text.y = element_text(size=9),
        axis.title.y = element_text(size=9)) +
  theme(axis.text.x = element_text(size=9)) +
  scale_x_discrete(limits=c("Reportedly Available","Locatable Data","Correct Data","Complete Data", "Codebook Available", "Software Specified", "Scripts Available"))+
  ylab("Percentage of Articles with Data Reportedly Available") +
  theme(legend.position=c(.125, .16)) +
  theme(legend.title=element_blank()) +
  theme(legend.text = element_text(size = 8)) +
  theme(legend.key.size = unit(1, "cm")) +
  guides(colour = guide_legend(override.aes = list(size = 2, shape = NA))) +
  theme(axis.line= element_line(), axis.title.x=element_blank(), 
        panel.background = element_blank(), 
        panel.grid.minor = element_blank()) 

plot

```

# MATERIALS

Select only the variables we're interested in

```{r}
select_materials <- subfield_groups %>%
  select(article_id_number, subfield_groups, statement_indicates_that_materials_are, are_the_materials_located_at_the_working_page, do_the_materials_correspond_to_what_is_reported_in_the_article, are_the_materials_complete, are_analysis_scripts_included_with_the_materials)
```

Let's create some summary tables

```{r}
# reportedly available
reportedly_available_data <- select_materials %>%
  filter(statement_indicates_that_materials_are == "Available") %>%
  tabyl(subfield_groups, statement_indicates_that_materials_are) %>%
  mutate("Percent" = Available/(Available)*100) %>%
  select(subfield_groups, Number = Available, Percent) %>%
  mutate(Real_Stage = "Reportedly Available")
```

