---
title: "Study 1B Exploratory Analysis - Raincloud Plots"
output: html_document
---

```{r message=FALSE, warning=FALSE, include=FALSE}
# Load packages

library(tidyverse)
library(janitor)
library(here)
library(patchwork)
source("R_rainclouds.R")
library(ggeasy)
library(gghalves)
set.seed(1)
```

# Study 1A Plots (2014-15)

```{r message=FALSE, warning=FALSE, include=FALSE}
options(scipen=999) # remove scientific notation

## Read in data

data1A <- read_csv(here("Working", "data_files", "Scored Study 1A Master Dataset.csv"))

# Note: you will need to change the location of the file, depending on where you have saved it
```


```{r include=FALSE}
# Assign articles to subfield groups

subfield_groups_data <- data1A %>%
  mutate(subfield_groups = case_when(subfield == "Behavioural Neuroscience" ~ "Other",
                                     subfield == "Cognitive Neuroscience" ~ "Other",
                                     subfield == "Health Psychology" ~ "Other",
                                     subfield == "Perception" ~ "Other",
                                     subfield == "Developmental Psychology" ~ "Development",
                                     subfield == "Social Psychology" ~  "Social",
                                     TRUE ~ as.character(subfield))) %>%
  relocate(subfield_groups, .after = subfield)

# Delete the original subfield column
subfield_groups_data <- subfield_groups_data %>%
  select(-subfield)
```


```{r message=FALSE, include=FALSE}

## Select relevant data 

final1A <- subfield_groups_data %>%
  select(article_id_number, subfield_groups, open_data_score, open_materials_score)

# Setting the subfield variable as a factor

final1A$subfield_groups <- fct_relevel(final1A$subfield_groups, c("Development", "Social", "Cognition", "Other"))

```

## Data Plot

```{r echo=FALSE}

# Note: We tried using the raincloud package function, but it only allowed us to compare two subfields at a time

dataplot1 <- final1A %>%  
  ggplot(aes(x = subfield_groups, y = open_data_score, fill = subfield_groups)) +
  geom_flat_violin(position = position_nudge(x = 0.025, y = 0),adjust = 0.5, alpha = 0.5) +
  geom_half_point(alpha = .3, size = 1, range_scale = 1, position = position_nudge(x = -0.4, y = 0)) +
    theme_classic() +
    theme(axis.title.y = element_text(size=9)) +
  scale_fill_manual(values=c("#EC407A","#42A5F5", "#FFCC33", "#00CC99")) +
  scale_x_discrete(labels=c("Development" = "Development\n(n = 65)","Social" = "Social\n(n = 91)","Cognition" = "Cognition\n(n = 91)","Other" = "Other\n(n = 75)")) +
  labs(x = element_blank(), y = 'Open Data Score') +
  easy_remove_legend() + 
  ggtitle('(a)')

dataplot1

```

## Materials Plot

```{r echo=FALSE}

materialsplot1 <- final1A %>%  
  ggplot(aes(x = subfield_groups, y = open_materials_score, fill = subfield_groups)) +
  geom_flat_violin(position = position_nudge(x = 0.025, y = 0),adjust = 0.5, alpha = 0.5) +
  geom_half_point(alpha = .3, size = 1, range_scale = 1, position = position_nudge(x = -0.4, y = 0)) +
    theme_classic() +
    theme(axis.title.y = element_text(size=9)) +
  scale_fill_manual(values=c("#EC407A","#42A5F5", "#FFCC33", "#00CC99")) +
  scale_x_discrete(labels=c("Development" = "Development\n(n = 65)","Social" = "Social\n(n = 91)","Cognition" = "Cognition\n(n = 91)","Other" = "Other\n(n = 75)")) +
  labs(x = element_blank(), y = 'Open Materials Score') +
  easy_remove_legend() + 
  ggtitle('(b)')

materialsplot1

```


# Study 1B Plots (2019-20)


```{r include=FALSE}
## Read in data

data1B <- read_csv(here("Working", "data_files", "Scored Study 1B Master Dataset.csv"))
```


```{r include=FALSE}
# Assign articles to subfield groups

subfield_groups_materials <- data1B %>%
  mutate(subfield_groups = case_when(subfield == "Behavioural Neuroscience" ~ "Other",
                                     subfield == "Cognitive Neuroscience" ~ "Other",
                                     subfield == "Health Psychology" ~ "Other",
                                     subfield == "Perception" ~ "Other",
                                     subfield == "Developmental Psychology" ~ "Development",
                                     subfield == "Social Psychology" ~  "Social",
                                     TRUE ~ as.character(subfield))) %>%
  relocate(subfield_groups, .after = subfield)

# Delete the original subfield column
subfield_groups_materials <- subfield_groups_materials %>%
  select(-subfield)
```


```{r include=FALSE}
## Select relevant data 

final1B <- subfield_groups_materials %>%
  select(article_id_number, subfield_groups, open_data_score, open_materials_score)

# Setting the subfield variable as a factor

final1B$subfield_groups <- fct_relevel(final1B$subfield_groups, c("Development", "Social", "Cognition", "Other"))

```

## Data Plot

```{r echo=FALSE}


dataplot2 <- final1B %>%  
  ggplot(aes(x = subfield_groups, y = open_data_score, fill = subfield_groups)) +
  geom_flat_violin(position = position_nudge(x = 0.025, y = 0),adjust = 0.5, alpha = 0.5) +
  geom_half_point(alpha = .3, size = 1, range_scale = 1, position = position_nudge(x = -0.4, y = 0)) +
    theme_classic() +
    theme(axis.title.y = element_text(size=9)) +
  scale_fill_manual(values=c("#EC407A","#42A5F5", "#FFCC33", "#00CC99")) +
  scale_x_discrete(labels=c("Development" = "Development\n(n = 34)","Social" = "Social\n(n = 57)","Cognition" = "Cognition\n(n = 61)","Other" = "Other\n(n = 41)")) +
  labs(x = element_blank(), y = 'Open Data Score') +
  easy_remove_legend() + 
  ggtitle('(c)')

dataplot2
```

## Materials Plot

```{r echo=FALSE}

materialsplot2 <- final1B %>%  
  ggplot(aes(x = subfield_groups, y = open_materials_score, fill = subfield_groups)) +
  geom_flat_violin(position = position_nudge(x = 0.025, y = 0),adjust = 0.5, alpha = 0.5) +
  geom_half_point(alpha = .3, size = 1, range_scale = 1, position = position_nudge(x = -0.4, y = 0)) +
    theme_classic() +
  theme(axis.title.y = element_text(size=9)) +
  scale_fill_manual(values=c("#EC407A","#42A5F5", "#FFCC33", "#00CC99")) +
  scale_x_discrete(labels=c("Development" = "Development\n(n = 34)","Social" = "Social\n(n = 57)","Cognition" = "Cognition\n(n = 61)","Other" = "Other\n(n = 41)")) +
  labs(x = element_blank(), y = 'Open Materials Score') +
  easy_remove_legend() + 
  ggtitle('(d)')

materialsplot2
```

# Figure 8

```{r echo=FALSE}
(dataplot1 | materialsplot1) / 
(dataplot2 | materialsplot2)
```

