# Load packages
library(qualtRics)
library(tidyverse)
library(janitor)
library(ggplot2)
library(grid)
library(cowplot)
library(httr)
library(extrafont)
library(here)
library(Hmisc)

# Read in Reliability Checking data

data <- read_csv(here("data_files", "data1B_reliability_checking"))

#### Subfield

# Let's assign the articles to a subfield

psyc_subfield <- data %>%
  mutate(subfield = case_when("Animals" == participants ~ "Behavioural Neuroscience", 
                              "Humans" == participants & "0-18 years or 65 years+" == age ~ "Developmental Psychology", 
                              "Humans" == participants & "Brain" == brain_beh  ~ "Cognitive Neuroscience",
                              "Humans" == participants & brain_beh %in% c("Both", "Behaviour") & "Sensation" == topic ~ "Perception",
                              "Humans" == participants & brain_beh %in% c("Both", "Behaviour") & "Emotion, personality, social behaviour" == topic ~ "Social Psychology",
                              "Humans" == participants & brain_beh %in% c("Both", "Behaviour") & "Intelligence, memory, decision making, reasoning, language, problem solving, creative thinking" == topic ~ "Cognition",
                              "Humans" == participants & brain_beh %in% c("Both", "Behaviour") & "Fitness, weight, consumption, hormone levels, chemical uptake, sleeping patterns" == topic ~ "Health Psychology")) %>%
  relocate(subfield, .after = no_of_experiments)

##### Data Scoring

# Now let's score the articles

# scoring
# low items = 1
# med items = 2
# high items = 5

#First we need to change data_page_no to a character variable (from a numeric variable)
psyc_subfield <- transform(psyc_subfield, "data_page_no" = as.character(data_page_no))

# Next we need to make the relevant data long
data_scoring <- psyc_subfield %>%
  select(article_id_number, subfield, data_badge, software, data_statement_present, data_statement_indicates, data_accessible, dataset_URL_working, data_locatable, data_downloadable, data_correspond, data_complete, data_codebook, data_scripts) %>%
  pivot_longer(names_to = "question", values_to = "response", software:data_scripts)

# Now let's assign scores for openness of data
data_scored_for_data <- data_scoring %>%
  mutate(data_score = case_when(question == "software" & response == "No" ~ 0, 
                                question == "software" & response == "Yes" ~ 0, 
                                question == "data_statement_present" & response == "No" ~ 0, 
                                question == "data_statement_present" & response == "Yes" ~ 1,
                                question == "data_statement_indicates" & response == "Unavailable" ~ 0, 
                                question == "data_statement_indicates" & response == "Available" ~ 1,
                                
                                question == "data_accessible" & response == "Not clear" ~ 0, 
                                question == "data_accessible" & response %in% c("Public dataset generated by the authors", "Public dataset generated by others", "Other (please specify):") ~ 2, 
                                question == "dataset_URL_working" & response == "No" ~ 0, 
                                question == "dataset_URL_working" & response == "Yes" ~ 2,
                                question == "data_locatable" & response == "No" ~ 0,
                                question == "data_locatable" & response == "Requires permission" ~ 1, 
                                question == "data_locatable" & response == "Yes" ~ 2,
                                question == "data_downloadable" & response == "No" ~ 0,
                                question == "data_downloadable" & response == "Requires permission" ~ 1, 
                                question == "data_downloadable" & response == "Yes" ~ 2,
                                question == "data_correspond" & response %in% c("Unclear", "No") ~ 0, 
                                question == "data_correspond" & response == "Yes" ~ 2,
                                question == "data_complete" & response %in% c("Unclear whether or not all the data are available", "No, not all of the data are available") ~ 0, 
                                question == "data_complete" & response == "Yes, but only some of the data are available" ~ 1, 
                                question == "data_complete" & response == "Yes, all of the data appear to be available" ~ 2,
                                
                                question == "data_codebook" & response == "No" ~ 0, 
                                question == "data_codebook" & response == "Yes" ~ 5,
                                question == "data_scripts" & response == "No" ~ 0, 
                                question == "data_scripts" & response == "Yes" ~ 5)) %>%
  mutate(data_score = coalesce(data_score, 0))

# Let's create a single open data score for each article 

open_data_score_summary <- data_scored_for_data %>%
  group_by(article_id_number, data_badge, subfield) %>% 
  summarise(total_data_score = sum(data_score))

open_data_score_summary %>%
  tabyl(total_data_score)

#### Material Scoring

# And let's assign scores for openness of materials 

# Let's make the relevant data long
materials_scoring <- psyc_subfield %>%
  select(article_id_number, subfield, materials_badge, materials_statement_present, materials_statement_indicates, materials_accessible, materials_URL_working, materials_locatable, materials_downloadable, materials_correspond, materials_complete, materials_explanation) %>%
  pivot_longer(names_to = "question", values_to = "response", materials_statement_present:materials_explanation)

# And let's score the data
data_scored_for_materials <- materials_scoring %>%
  mutate(materials_score = case_when(question == "materials_statement_present" & response =="No" ~ 0,
                                     question == "materials_statement_present"  &  response == "Yes" ~ 1, 
                                     question == "materials_statement_indicates" & response =="Unavailable" ~ 0,
                                     question == "materials_statement_indicates"  &  response == "Available" ~ 1, 
                                     
                                     question == "materials_accessible" & response =="Not clean" ~ 0,
                                     question == "materials_accessible"  &response %in% c("Public set of materials generated by authors", "Public set of materials generated by others", "Other (please specify):") ~ 2, 
                                     question == "materials_URL_working" & response =="No" ~ 0,
                                     question == "materials_URL_working"  &  response == "Yes" ~ 2, 
                                     question == "materials_locatable"  & response== "No" ~ 0,
                                     question == "materials_locatable" & response == "Requires permission" ~ 1,
                                     question == "materials_locatable" & response == "Yes" ~ 2,
                                     question == "materials_downloadable"  & response== "No" ~ 0,
                                     question == "materials_downloadable" & response == "Requires permission" ~ 1,
                                     question == "materials_downloadable" & response == "Yes" ~ 2,
                                     question == "materials_correspond" & response %in% c("Unclear", "No") ~ 0,
                                     question == "materials_correspond" & response == "Yes" ~ 2,
                                     question == "materials_complete" & response %in% c("Unclear whether or not all the materials are available", "No, not all of the materials are available") ~ 0,
                                     question == "materials_complete" & response == "Yes, but only some of the materials are available" ~ 1,
                                     question == "materials_complete" & response == "Yes, all of the materials appear to be available" ~ 2,
                                     
                                     question == "materials_explanation" & response == "No" ~ 0,
                                     question == "materials_explanation" & response == "Yes" ~ 5))  %>%
  mutate(materials_score = coalesce(materials_score, 0))

# Let's create a single open materials score for each article 

open_materials_score_summary <- data_scored_for_materials %>%
  group_by(article_id_number, materials_badge, subfield) %>% 
  summarise(total_materials_score = sum(materials_score))

open_materials_score_summary %>%
  tabyl(total_materials_score)

#### Checking reliability

# let's put the data in an appropriate format
Christina = c(Checker 1B score, Checker 2B score, Checker 3B score, Checker 4B score, Checker 5B score)
Georgia = c(Checker 1B score, Checker 2B score, Checker 3B score)
Jenn = c(Checker 1B score, Checker 2B score, Checker 3B score)
Helen = c(Checker 1B score, Checker 2B score, Checker 3B score)
Will = c(Checker 1B score, Checker 2B score, Checker 3B score)
Patrick = c(Checker 1B score, Checker 2B score, Checker 3B score)

# I was the only coder who coded all 5 checker articles (some coders coded 1, others coded 2, and other coded 3) - does this matter?

# join coders data together
reliability_data_scored <- cbind(rater1,rater2)

# make it a data frame
reliability_data_scored <- as.data.frame(reliability_data_scored) 
# will this dataframe contain an article_id_number column?

# calc kappa
cohen.kappa(reliability_data_scored)





