---
title: "reliability_notes"
author: "Jen Richmond"
date: "15/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Example from psych docs

```{r}
library(psych)
```


This example comes from here...

https://www.datanovia.com/en/lessons/cohens-kappa-in-r-for-two-categorical-variables/

```{r}

diagnoses <- as.table(rbind(
  c(7, 1, 2, 3, 0), c(0, 8, 1, 1, 0),
  c(0, 0, 2, 0, 0), c(0, 0, 0, 1, 0),
  c(0, 0, 0, 0, 4)
  ))


categories <- c("Depression", "Personality Disorder",
                "Schizophrenia", "Neurosis", "Other")

dimnames(diagnoses) <- list(Doctor1 = categories, Doctor2 = categories)

diagnoses

# install.packages("vcd")
library("vcd")

# Compute kapa
res.k <- Kappa(diagnoses)
res.k



```

https://cran.rstudio.com/web/packages/psych/psych.pdf


```{r}
#rating data (with thanks to Tim Bates)
rater1 = c(1,2,3,4,5,6,7,8,9) # rater one's ratings

rater2 = c(1,3,1,6,1,5,5,6,7) # rater one's ratings

# join raters data together
x <- cbind(rater1,rater2)

# make it a data frame
x <- as.data.frame(x)

# calc kappa
cohen.kappa(x)

```

What if there were more than 2 raters??

```{r}
rater1 = c(1,2,3,4,1,6,4,8,9) # rater 1 ratings

rater2 = c(1,3,1,6,1,5,5,7,7) # rater 2 ratings

rater3 = c(2,3,2,5,1,5,5,8,9) # rater 3 ratings

rater4 = c(1,2,3,4,2,7,5,9,7) # rater 4 ratings

rater5 = c(2,3,2,5,1,5,6,8,7) # rater 5ratings
```

```{r}
# join raters data together
y <- cbind(rater1, rater2, rater3, rater4, rater5)

# make it a data frame
y <- as.data.frame(y)

# calc kappa

cohen.kappa(y)
```


Hmmm not sure whether that warning is important... lets do what it says...

```{r}
describe(y)
```

